/**
 * 标题 → URL Slug 生成器
 * 策略：中英文词典匹配 + 未匹配中文移除 + 清理输出
 * 示例：伊朗冲突持续多久？油价会涨到多少？对美股港股有何具体影响？
 *     → how-long-iran-conflict-oil-price-impact-us-hk-stocks
 */

const pinyinMap: { [key: string]: string } = {
  // ── 疑问词/虚词 ──
  '什么是':    'what-is',
  '为什么':    'why',
  '如何':      'how-to',
  '怎么':      'how',
  '怎么样':    'how',
  '多少':      'how-much',
  '多久':      'how-long',
  '什么时候':  'when',
  '何时':      'when',
  '哪里':      'where',
  '哪个':      'which',
  '哪些':      'which',
  '能否':      'can',
  '可以':      'can',
  '应该':      'should',
  '需要':      'need',
  '值得':      'worth',
  '有没有':    'has',
  '是不是':    'is',
  '会':        'will',
  '要':        'will',
  '能':        'can',
  '有':        'has',
  '是':        'is',
  '对':        '',
  '的':        '',
  '了':        '',
  '吗':        '',
  '呢':        '',
  '吧':        '',
  '啊':        '',
  '呀':        '',
  '？':        '',
  '！':        '',
  '，':        '',
  '。':        '',
  '、':        '',
  '：':        '',
  '\uff1b':        '',
  '\u201c':         '',
  '\u201d':         '',
  '\u2018':         '',
  '\u2019':         '',
  '\uff08':        '',
  '\uff09':        '',
  '\u3010':        '',
  '\u3011':        '',
  '\u300a':        '',
  '\u300b':        '',

  // ── 金融/经济 ──
  '美联储':    'fed',
  '联储':      'fed',
  '利率':      'rate',
  '基准利率':  'benchmark-rate',
  '政策利率':  'policy-rate',
  '贴现率':    'discount-rate',
  '政策':      'policy',
  '资产':      'asset',
  '配置':      'allocation',
  '股票':      'stock',
  '股市':      'stock-market',
  '市场':      'market',
  '经济':      'economy',
  '通胀':      'inflation',
  '通货紧缩':  'deflation',
  '就业':      'employment',
  '失业':      'unemployment',
  '劳动力':    'labor',
  '美元':      'usd',
  '美元指数':  'dxy',
  '人民币':    'cny',
  '欧元':      'eur',
  '英镑':      'gbp',
  '日元':      'jpy',
  '港币':      'hkd',
  '汇率':      'exchange-rate',
  '债券':      'bond',
  '国债':      'treasury',
  '美债':      'us-treasury',
  '基金':      'fund',
  'ETF':       'etf',
  '期货':      'futures',
  '期权':      'options',
  '投资':      'invest',
  '理财':      'finance',
  '宏观':      'macro',
  '微观':      'micro',
  '解读':      'analysis',
  '分析':      'analysis',
  '预测':      'forecast',
  '影响':      'impact',
  '趋势':      'trend',
  '数据':      'data',
  '报告':      'report',
  '会议':      'meeting',
  '声明':      'statement',
  '决议':      'decision',
  '加息':      'rate-hike',
  '降息':      'rate-cut',
  '维持':      'hold',
  '不变':      'unchanged',
  '增长':      'growth',
  '衰退':      'recession',
  '复苏':      'recovery',
  '滞胀':      'stagflation',
  '风险':      'risk',
  '机会':      'opportunity',
  '策略':      'strategy',
  '建议':      'advice',
  '指南':      'guide',
  '教程':      'tutorial',
  '问答':      'qa',
  '解释':      'explain',
  '买':        'buy',
  '卖':        'sell',
  '持有':      'hold',
  '加仓':      'add-position',
  '减仓':      'reduce-position',
  '抄底':      'buy-bottom',
  '止损':      'stop-loss',
  '止盈':      'take-profit',
  '反弹':      'rebound',
  '回调':      'pullback',
  '突破':      'breakout',
  '支撑':      'support',
  '压力':      'resistance',
  '波动':      'volatility',
  '上涨':      'rise',
  '下跌':      'fall',
  '震荡':      'sideways',
  '盘整':      'consolidation',
  '放量':      'volume-up',
  '缩量':      'volume-down',
  '资金':      'capital',
  '流向':      'flow',
  '北向':      'northbound',
  '南向':      'southbound',
  '外资':      'foreign',
  '内资':      'domestic',
  '机构':      'institutional',
  '散户':      'retail',
  '情绪':      'sentiment',
  '预期':      'expectation',
  '实际':      'actual',
  '公布':      'release',
  '发布':      'publish',
  '初请':      'initial-claims',
  '非农':      'nfp',
  'GDP':       'gdp',
  'CPI':       'cpi',
  'PCE':       'pce',
  'PMI':       'pmi',
  'FOMC':      'fomc',
  '收益率':    'yield',
  '利差':      'spread',
  '流动性':    'liquidity',
  '估值':      'valuation',
  '市盈率':    'pe-ratio',
  '股息':      'dividend',
  '回购':      'buyback',
  'IPO':       'ipo',
  '新股':      'ipo',
  '涨停':      'limit-up',
  '跌停':      'limit-down',
  '熔断':      'circuit-breaker',
  '黑天鹅':    'black-swan',
  '牛市':      'bull',
  '熊市':      'bear',
  '油价':      'oil-price',
  '金价':      'gold-price',
  '铜价':      'copper-price',
  '比特币':    'bitcoin',
  '以太坊':    'ethereum',
  '加密货币':  'crypto',
  '数字货币':  'crypto',
  '区块链':    'blockchain',
  '现货':      'spot',
  '合约':      'contract',
  '杠杆':      'leverage',
  '做空':      'short',
  '做多':      'long',
  '套利':      'arbitrage',
  '对冲':      'hedge',
  '选股':      'stock-picking',
  '仓位':      'position',
  '持仓':      'position',
  '换手率':    'turnover',
  '成交额':    'turnover-value',
  '成交量':    'volume',
  '市值':      'market-cap',
  '营收':      'revenue',
  '利润':      'profit',
  '财报':      'earnings',
  '业绩':      'earnings',
  '分红':      'dividend',
  '派息':      'dividend',
  '配股':      'rights-issue',
  '增发':      'additional-issue',

  // ── 地名/地区 ──
  '中国':      'china',
  '美国':      'us',
  '美股':      'us-stocks',
  '港股':      'hk-stocks',
  'A股':       'a-shares',
  '日本':      'japan',
  '韩国':      'korea',
  '欧洲':      'europe',
  '英国':      'uk',
  '德国':      'germany',
  '法国':      'france',
  '印度':      'india',
  '俄罗斯':    'russia',
  '巴西':      'brazil',
  '东南亚':    'southeast-asia',
  '全球':      'global',
  '亚太':      'asia-pacific',
  '中东':      'middle-east',
  '伊朗':      'iran',
  '以色列':    'israel',
  '乌克兰':    'ukraine',
  '台湾':      'taiwan',
  '香港':      'hong-kong',
  '上海':      'shanghai',
  '深圳':      'shenzhen',
  '北京':      'beijing',
  '纳斯达克':  'nasdaq',
  '标普':      'spx',
  '道琼斯':    'dow',
  '恒生':      'hang-seng',
  '上证':      'shanghai-composite',
  '深证':      'shenzhen-component',
  '沪深300':   'csi300',

  // ── 行业/板块 ──
  '科技':      'tech',
  '科技股':    'tech-stocks',
  '互联网':    'internet',
  '半导体':    'semiconductor',
  '芯片':      'chip',
  '人工智能':  'ai',
  '新能源':    'new-energy',
  '光伏':      'solar',
  '电动车':    'ev',
  '房地产':    'real-estate',
  '医药':      'pharma',
  '消费':      'consumer',
  '银行':      'banking',
  '保险':      'insurance',
  '券商':      'brokerage',
  '军工':      'defense',
  '能源':      'energy',
  '石油':      'oil',
  '天然气':    'natural-gas',
  '煤炭':      'coal',
  '钢铁':      'steel',
  '有色金属':  'metals',
  '农业':      'agriculture',
  '食品':      'food',

  // ── 公司 ──
  '阿里巴巴':  'alibaba',
  '腾讯':      'tencent',
  '百度':      'baidu',
  '京东':      'jd',
  '美团':      'meituan',
  '拼多多':    'pdd',
  '小米':      'xiaomi',
  '华为':      'huawei',
  '字节':      'bytedance',
  '抖音':      'douyin',
  '快手':      'kuaishou',
  '头条':      'toutiao',
  '网易':      'netease',
  '新浪':      'sina',
  '搜狐':      'sohu',
  '携程':      'ctrip',
  '蔚来':      'nio',
  '理想':      'lixiang',
  '小鹏':      'xpeng',
  '比亚迪':    'byd',
  '宁德':      'catl',
  '茅台':      'maotai',
  '五粮液':    'wuliangye',
  '苹果':      'apple',
  '微软':      'microsoft',
  '谷歌':      'google',
  '亚马逊':    'amazon',
  '特斯拉':    'tesla',
  '英伟达':    'nvidia',
  '台积电':    'tsmc',

  // ── 银行 ──
  '工商':      'icbc',
  '建设':      'ccb',
  '招商':      'cmb',
  '浦发':      'spdb',
  '民生':      'cmbc',
  '兴业':      'cib',
  '平安':      'pingan',
  '中行':      'boc',
  '交行':      'bocom',
  '邮储':      'psbc',

  // ── 时间 ──
  '今年':      'this-year',
  '明年':      'next-year',
  '去年':      'last-year',
  '上半年':    'first-half',
  '下半年':    'second-half',
  '第一季度':  'q1',
  '第二季度':  'q2',
  '第三季度':  'q3',
  '第四季度':  'q4',
  '季度':      'quarter',
  '月':        'month',
  '周':        'week',
  '天':        'day',
  '年':        'year',

  // ── 动词/形容词 ──
  '冲突':      'conflict',
  '战争':      'war',
  '制裁':      'sanctions',
  '谈判':      'negotiation',
  '协议':      'agreement',
  '贸易战':    'trade-war',
  '关税':      'tariff',
  '出口':      'export',
  '进口':      'import',
  '供应':      'supply',
  '需求':      'demand',
  '短缺':      'shortage',
  '过剩':      'surplus',
  '危机':      'crisis',
  '持续':      '',
  '具体':      '',
  '相关':      'related',
  '最新':      'latest',
  '重要':      'important',
  '关键':      'key',
  '核心':      'core',
  '大幅':      'sharp',
  '小幅':      'mild',
  '快速':      'rapid',
  '缓慢':      'slow',
  '稳定':      'stable',
  '不稳定':    'unstable',
  '意外':      'unexpected',
  '超预期':    'beat-expectation',
  '低于预期':  'below-expectation',
  '符合预期':  'meet-expectation',
  '历史新高':  'all-time-high',
  '历史新低':  'all-time-low',
  '大幅上涨':  'surge',
  '大幅下跌':  'plunge',
  '暴跌':      'crash',
  '暴涨':      'soar',
  '回暖':      'warm-up',
  '触底':      'bottom-out',
  '见顶':      'peak',
  '反转':      'reversal',
  '调整':      'correction',
  '涨到':      'rise-to',
  '涨':        'rise',
  '跌':        'fall',
}

export function generateSlugFromTitle(title: string): string {
  if (!title) return ''

  let text = title.trim()

  // 移除纯标点/特殊字符，保留中文、英文、数字、空格
  text = text.replace(/[^\w\u4e00-\u9fa5\s]/g, ' ')

  // 按词长度降序匹配（长词优先，避免"美联储"被拆成"美"+"联储"）
  const sortedKeys = Object.keys(pinyinMap).sort((a, b) => b.length - a.length)
  for (const key of sortedKeys) {
    text = text.replace(new RegExp(escapeRegex(key), 'g'), ' ' + pinyinMap[key] + ' ')
  }

  // 移除未匹配的残留中文字符
  text = text.replace(/[\u4e00-\u9fa5]/g, ' ')

  // 清理：转小写、去多余空格、连字符连接
  text = text.toLowerCase()
  text = text.replace(/[^a-z0-9\s-]/g, ' ')
  text = text.replace(/\s+/g, ' ').trim()
  text = text.replace(/\s+/g, '-')

  // 去首尾连字符、去连续连字符
  text = text.replace(/-+/g, '-')
  text = text.replace(/^-+|-+$/g, '')

  // 兜底
  if (text === '') {
    return 'post-' + Date.now()
  }

  return text
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export function validateSlug(slug: string): boolean {
  if (!slug) return false
  return /^[a-z0-9-]+$/.test(slug)
}

export function sanitizeSlug(slug: string): string {
  return slug
    .toLowerCase()
    .replace(/[^\w-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
}
